---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Configure keystone in horizon
  lineinfile: dest=/etc/openstack-dashboard/local_settings.py
              regexp=^OPENSTACK_HOST
              line="OPENSTACK_HOST = '{{ keystone_hostname }}'"
  notify:
    - Restart apache2

- name: Configure secret key location
  lineinfile: dest=/etc/openstack-dashboard/local_settings.py
              regexp=^SECRET_KEY
              line="SECRET_KEY = secret_key.generate_or_read_from_file('/var/lib/openstack-dashboard/secret_key/key')"
  notify:
    - Restart apache2

- name: Setup horizon var dir
  file: dest=/var/lib/openstack-dashboard owner=horizon group=horizon mode=755 state=directory
  notify:
    - Restart apache2

- name: Setup horizon secret key dir
  file: dest=/var/lib/openstack-dashboard/secret_key owner=www-data group=www-data mode=755 state=directory
  notify:
    - Restart apache2

- name: Disable default apache config
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - Restart apache2

- name: Disable the default config in Ubuntu
  file: path=/etc/apache2/conf-enabled/openstack-dashboard.conf state=absent
  notify:
    - Restart apache2

- name: Write default openstack horizon apache config
  copy: dest=/etc/apache2/sites-available/openstack-dashboard.conf src=openstack-dashboard.conf mode=644 owner=root group=root
  notify:
    - Restart apache2

- name: Enable openstack horizon apache config
  file: path=/etc/apache2/sites-enabled/openstack-dashboard.conf state=link src=/etc/apache2/sites-available/openstack-dashboard.conf
  notify:
    - Restart apache2
